services:
  _defaults:
    public: true

  prestashop.module.aa_endpointforsc.carrier_mapping.repository:
    class: PrestaShop\Module\AaEndpointForSc\Repository\CarrierMappingRepository
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
      $languages: '@=service("prestashop.adapter.legacy.context").getLanguages(true, service("prestashop.adapter.shop.context").getContextShopID())'
      $translator: '@translator'

  prestashop.module.aa_endpointforsc.carrier_mapping.form_handler:
    class: PrestaShop\PrestaShop\Core\Form\FormHandler
    arguments:
      $formBuilder: '@=service("form.factory").createBuilder()'
      $hookDispatcher: '@prestashop.core.hook.dispatcher'
      $formDataProvider: '@prestashop.module.aa_endpointforsc.carrier_mapping.form_provider'
      $formTypes:
        'carrier_mapping': 'PrestaShop\Module\AaEndpointForSc\Form\Type\CarrierMappingType'
      $hookName: 'AdminLinkWidget'

  prestashop.module.aa_endpointforsc.carrier_mapping.form_type:
    class: PrestaShop\Module\AaEndpointForSc\Form\Type\CarrierMappingType
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      $translator: '@translator'
      $repository: '@prestashop.module.aa_endpointforsc.carrier_mapping.repository'
    tags:
      - { name: form.type }

  prestashop.module.aa_endpointforsc.carrier_mapping.form_provider:
    class: PrestaShop\Module\AaEndpointForSc\Form\CarrierMappingFormDataProvider
    arguments:
      $repository: '@prestashop.module.aa_endpointforsc.carrier_mapping.repository'
      $cache: '@prestashop.module.aa_endpointforsc.cache'
      $languages: '@=service("prestashop.adapter.legacy.context").getLanguages(true, service("prestashop.adapter.shop.context").getContextShopID())'
      $shopId: '@=service("prestashop.adapter.shop.context").getContextShopID()'


  prestashop.module.aa_endpointforsc.cache:
    class: PrestaShop\Module\AaEndpointForSc\Cache\LegacyLinkBlockCache


  prestashop.module.aa_endpointforsc.choice_provider.carrier:
    class: 'PrestaShop\Module\AaEndpointForSc\Form\Provider\CarrierChoiceProvider'


  prestashop.module.aa_endpointforsc.type.carrier_choice:
    class: 'PrestaShop\Module\AaEndpointForSc\Form\Type\CarrierMappingType'
    arguments:
      - '@translator'
      - '@=service("prestashop.adapter.legacy.context").getLanguages(true, service("prestashop.adapter.shop.context").getContextShopID())'
      - "@prestashop.module.aa_endpointforsc.carrier_mapping.repository"
      - "@prestashop.module.aa_endpointforsc.choice_provider.carrier"

    tags:
      - { name: form.type }

  prestashop.module.aa_endpointforsc.sendcloud_carriers:
    class: 'PrestaShop\Module\AaEndpointForSc\Services\Carriers\SendCloudCarriers'
